// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_AddToCartButton from "./islands/AddToCartButton/AddToCartButton.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $BrowserLog from "./islands/BrowserLog.tsx";
import * as $ClearSearchFilters from "./islands/ClearSearchFilters.tsx";
import * as $CoverFlowSlider from "./islands/CoverFlowSlider.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_CartDrawer from "./islands/Header/CartDrawer.tsx";
import * as $Header_FreeShippingProgressBar from "./islands/Header/FreeShippingProgressBar.tsx";
import * as $Header_MenuDrawer from "./islands/Header/MenuDrawer.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $Header_SetupMicroHeader from "./islands/Header/SetupMicroHeader.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductActions_vtex from "./islands/ProductActions/vtex.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $ShowMore from "./islands/ShowMore.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $Video from "./islands/Video.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import * as $ZoomableImage from "./islands/ZoomableImage.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/AddToCartButton.tsx":
      $AddToCartButton_AddToCartButton,
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/BrowserLog.tsx": $BrowserLog,
    "./islands/ClearSearchFilters.tsx": $ClearSearchFilters,
    "./islands/CoverFlowSlider.tsx": $CoverFlowSlider,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/CartDrawer.tsx": $Header_CartDrawer,
    "./islands/Header/FreeShippingProgressBar.tsx":
      $Header_FreeShippingProgressBar,
    "./islands/Header/MenuDrawer.tsx": $Header_MenuDrawer,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/Header/SetupMicroHeader.tsx": $Header_SetupMicroHeader,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductActions/vtex.tsx": $ProductActions_vtex,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/ShowMore.tsx": $ShowMore,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/Video.tsx": $Video,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
    "./islands/ZoomableImage.tsx": $ZoomableImage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
