// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$2 from "./loaders/availableCategories.ts";
import * as $$$3 from "./loaders/availableIcons.ts";
import * as $$$4 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$$$$$0 from "./matchers/canonical.ts";
import * as $$$$$$$1 from "./matchers/category.ts";
import * as $$$$$$$2 from "./matchers/categoryUrl.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$2 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$3 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$4 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$5 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$6 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$7 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$8 from "./sections/Content/Benefits.tsx";
import * as $$$$$$9 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$10 from "./sections/Content/BreadcrumbCustom.tsx";
import * as $$$$$$11 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$12 from "./sections/Content/Faq.tsx";
import * as $$$$$$13 from "./sections/Content/Features.tsx";
import * as $$$$$$14 from "./sections/Content/Hero.tsx";
import * as $$$$$$15 from "./sections/Content/HeroSlider.tsx";
import * as $$$$$$16 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$17 from "./sections/Content/Intro.tsx";
import * as $$$$$$18 from "./sections/Content/Logos.tsx";
import * as $$$$$$19 from "./sections/Content/Partners.tsx";
import * as $$$$$$20 from "./sections/Content/RichText.tsx";
import * as $$$$$$21 from "./sections/Content/Table.tsx";
import * as $$$$$$22 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$23 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$24 from "./sections/Content/Video.tsx";
import * as $$$$$$25 from "./sections/Footer/Footer.tsx";
import * as $$$$$$26 from "./sections/Gallery.tsx";
import * as $$$$$$27 from "./sections/Header/Header.tsx";
import * as $$$$$$28 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$29 from "./sections/Images/BannerMosaic.tsx";
import * as $$$$$$30 from "./sections/Images/Carousel.tsx";
import * as $$$$$$31 from "./sections/Images/CarouselMatcher.tsx";
import * as $$$$$$32 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$33 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$34 from "./sections/Institutional/Institutional.tsx";
import * as $$$$$$35 from "./sections/Institutional/InstitutionalMenu.tsx";
import * as $$$$$$36 from "./sections/Institutional/InstitutionalText.tsx";
import * as $$$$$$37 from "./sections/Layout/Spacing.tsx";
import * as $$$$$$38 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$39 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$40 from "./sections/LocaleInfo.tsx";
import * as $$$$$$41 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$42 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$43 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$44 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$45 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$46 from "./sections/Product/NotFound.tsx";
import * as $$$$$$47 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$48 from "./sections/Product/PdpDescription.tsx";
import * as $$$$$$49 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$50 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$51 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$52 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$53 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$54 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$55 from "./sections/Search/Breadcrumb.tsx";
import * as $$$$$$56 from "./sections/Search/TextSEO.tsx";
import * as $$$$$$57 from "./sections/Search/TextSEOMatcher.tsx";
import * as $$$$$$58 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$59 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$61 from "./sections/Theme/defaultColors.ts";
import * as $$$$$$62 from "./sections/Theme/theme.d.ts";
import * as $$$$$$60 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/todo-livro/loaders/availableCategories.ts": $$$2,
    "deco-sites/todo-livro/loaders/availableIcons.ts": $$$3,
    "deco-sites/todo-livro/loaders/icons.ts": $$$4,
    "deco-sites/todo-livro/loaders/Layouts/ProductCard.tsx": $$$0,
    "deco-sites/todo-livro/loaders/List/Sections.tsx": $$$1,
  },
  "sections": {
    "deco-sites/todo-livro/sections/Animation/Animation.tsx": $$$$$$0,
    "deco-sites/todo-livro/sections/Cards/IconCardsCarousel.tsx": $$$$$$1,
    "deco-sites/todo-livro/sections/Cards/IconCardsCarouselWithImage.tsx":
      $$$$$$2,
    "deco-sites/todo-livro/sections/Cards/ImageCardsCarousel.tsx": $$$$$$3,
    "deco-sites/todo-livro/sections/Cards/ImageCardsCarouselWithImage.tsx":
      $$$$$$4,
    "deco-sites/todo-livro/sections/Category/CategoryBanner.tsx": $$$$$$5,
    "deco-sites/todo-livro/sections/Category/CategoryGrid.tsx": $$$$$$6,
    "deco-sites/todo-livro/sections/Category/CategoryList.tsx": $$$$$$7,
    "deco-sites/todo-livro/sections/Content/Benefits.tsx": $$$$$$8,
    "deco-sites/todo-livro/sections/Content/BlogPosts.tsx": $$$$$$9,
    "deco-sites/todo-livro/sections/Content/BreadcrumbCustom.tsx": $$$$$$10,
    "deco-sites/todo-livro/sections/Content/CallToAction.tsx": $$$$$$11,
    "deco-sites/todo-livro/sections/Content/Faq.tsx": $$$$$$12,
    "deco-sites/todo-livro/sections/Content/Features.tsx": $$$$$$13,
    "deco-sites/todo-livro/sections/Content/Hero.tsx": $$$$$$14,
    "deco-sites/todo-livro/sections/Content/HeroSlider.tsx": $$$$$$15,
    "deco-sites/todo-livro/sections/Content/ImageSection.tsx": $$$$$$16,
    "deco-sites/todo-livro/sections/Content/Intro.tsx": $$$$$$17,
    "deco-sites/todo-livro/sections/Content/Logos.tsx": $$$$$$18,
    "deco-sites/todo-livro/sections/Content/Partners.tsx": $$$$$$19,
    "deco-sites/todo-livro/sections/Content/RichText.tsx": $$$$$$20,
    "deco-sites/todo-livro/sections/Content/Table.tsx": $$$$$$21,
    "deco-sites/todo-livro/sections/Content/Testimonials.tsx": $$$$$$22,
    "deco-sites/todo-livro/sections/Content/TextWithImage.tsx": $$$$$$23,
    "deco-sites/todo-livro/sections/Content/Video.tsx": $$$$$$24,
    "deco-sites/todo-livro/sections/Footer/Footer.tsx": $$$$$$25,
    "deco-sites/todo-livro/sections/Gallery.tsx": $$$$$$26,
    "deco-sites/todo-livro/sections/Header/Header.tsx": $$$$$$27,
    "deco-sites/todo-livro/sections/Images/BannerGrid.tsx": $$$$$$28,
    "deco-sites/todo-livro/sections/Images/BannerMosaic.tsx": $$$$$$29,
    "deco-sites/todo-livro/sections/Images/Carousel.tsx": $$$$$$30,
    "deco-sites/todo-livro/sections/Images/CarouselMatcher.tsx": $$$$$$31,
    "deco-sites/todo-livro/sections/Images/ImageGallery.tsx": $$$$$$32,
    "deco-sites/todo-livro/sections/Images/ShoppableBanner.tsx": $$$$$$33,
    "deco-sites/todo-livro/sections/Institutional/Institutional.tsx": $$$$$$34,
    "deco-sites/todo-livro/sections/Institutional/InstitutionalMenu.tsx":
      $$$$$$35,
    "deco-sites/todo-livro/sections/Institutional/InstitutionalText.tsx":
      $$$$$$36,
    "deco-sites/todo-livro/sections/Layout/Spacing.tsx": $$$$$$37,
    "deco-sites/todo-livro/sections/Links/LinkTree.tsx": $$$$$$38,
    "deco-sites/todo-livro/sections/Links/Shortcuts.tsx": $$$$$$39,
    "deco-sites/todo-livro/sections/LocaleInfo.tsx": $$$$$$40,
    "deco-sites/todo-livro/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$41,
    "deco-sites/todo-livro/sections/Miscellaneous/CookieConsent.tsx": $$$$$$42,
    "deco-sites/todo-livro/sections/Miscellaneous/Slide.tsx": $$$$$$43,
    "deco-sites/todo-livro/sections/Newsletter/Newsletter.tsx": $$$$$$44,
    "deco-sites/todo-livro/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$45,
    "deco-sites/todo-livro/sections/Product/NotFound.tsx": $$$$$$46,
    "deco-sites/todo-livro/sections/Product/NotFoundChallenge.tsx": $$$$$$47,
    "deco-sites/todo-livro/sections/Product/PdpDescription.tsx": $$$$$$48,
    "deco-sites/todo-livro/sections/Product/ProductDetails.tsx": $$$$$$49,
    "deco-sites/todo-livro/sections/Product/ProductShelf.tsx": $$$$$$50,
    "deco-sites/todo-livro/sections/Product/ProductShelfTabbed.tsx": $$$$$$51,
    "deco-sites/todo-livro/sections/Product/SearchResult.tsx": $$$$$$52,
    "deco-sites/todo-livro/sections/Product/ShelfWithImage.tsx": $$$$$$53,
    "deco-sites/todo-livro/sections/Product/Wishlist.tsx": $$$$$$54,
    "deco-sites/todo-livro/sections/Search/Breadcrumb.tsx": $$$$$$55,
    "deco-sites/todo-livro/sections/Search/TextSEO.tsx": $$$$$$56,
    "deco-sites/todo-livro/sections/Search/TextSEOMatcher.tsx": $$$$$$57,
    "deco-sites/todo-livro/sections/Social/InstagramPosts.tsx": $$$$$$58,
    "deco-sites/todo-livro/sections/Social/WhatsApp.tsx": $$$$$$59,
    "deco-sites/todo-livro/sections/Theme/defaultColors.ts": $$$$$$61,
    "deco-sites/todo-livro/sections/Theme/theme.d.ts": $$$$$$62,
    "deco-sites/todo-livro/sections/Theme/Theme.tsx": $$$$$$60,
  },
  "matchers": {
    "deco-sites/todo-livro/matchers/canonical.ts": $$$$$$$0,
    "deco-sites/todo-livro/matchers/category.ts": $$$$$$$1,
    "deco-sites/todo-livro/matchers/categoryUrl.ts": $$$$$$$2,
  },
  "apps": {
    "deco-sites/todo-livro/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/todo-livro/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/todo-livro",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
