import daisyui from "daisyui";
import { Config } from "npm:tailwindcss";

export default {
  // @ts-expect-error daisyui is a valid plugin
  plugins: [daisyui],
  daisyui: { themes: [], logs: false },
  content: ["./**/*.tsx"],
  corePlugins: {
    lineHeight: false,
  },
  theme: {
    container: { center: true },
    colors: {
      "primary-500": " oklch(var(--primary-500))",
      "primary-400": " oklch(var(--primary-400))",
      "primary-300": " oklch(var(--primary-300))",
      "primary-200": " oklch(var(--primary-200))",
      "primary-100": " oklch(var(--primary-100))",
      "secondary-500": " oklch(var(--secondary-500))",
      "secondary-400": " oklch(var(--secondary-400))",
      "secondary-300": " oklch(var(--secondary-300))",
      "secondary-200": " oklch(var(--secondary-200))",
      "secondary-100": " oklch(var(--secondary-100))",
      "neutral-700": " oklch(var(--neutral-700))",
      "neutral-600": " oklch(var(--neutral-600))",
      "neutral-500": " oklch(var(--neutral-500))",
      "neutral-400": " oklch(var(--neutral-400))",
      "neutral-300": " oklch(var(--neutral-300))",
      "neutral-200": " oklch(var(--neutral-200))",
      "neutral-100": " oklch(var(--neutral-100))",
      "danger-500": " oklch(var(--danger-500))",
      "danger-400": " oklch(var(--danger-400))",
      "danger-300": " oklch(var(--danger-300))",
      "danger-200": " oklch(var(--danger-200))",
      "danger-100": " oklch(var(--danger-100))",
      "warning-500": " oklch(var(--warning-500))",
      "warning-400": " oklch(var(--warning-400))",
      "warning-300": " oklch(var(--warning-300))",
      "warning-200": " oklch(var(--warning-200))",
      "warning-100": " oklch(var(--warning-100))",
      "success-500": " oklch(var(--success-500))",
      "success-400": " oklch(var(--success-400))",
      "success-300": " oklch(var(--success-300))",
      "success-200": " oklch(var(--success-200))",
      "success-100": " oklch(var(--success-100))",
      "info-500": " oklch(var(--info-500))",
      "info-400": " oklch(var(--info-400))",
      "info-300": " oklch(var(--info-300))",
      "info-200": " oklch(var(--info-200))",
      "info-100": " oklch(var(--info-100))",
    },
    extend: {
      fontSize: {
        xs: ["0.75rem", {}],
        sm: ["0.875rem", {}],
        base: ["1rem", {}],
        lg: ["1.125rem", {}],
        xl: ["1.25rem", {}],
        "2xl": ["1.5rem", {}],
        "3xl": ["1.875rem", {}],
        "4xl": ["2.25rem", {}],
        "5xl": ["3rem", {}],
        "6xl": ["3.75rem", {}],
        "7xl": ["4.5rem", {}],
        "8xl": ["6rem", {}],
        "9xl": ["8rem", {}],
      },
      animation: {
        sliding: "sliding 30s linear infinite",
      },
      keyframes: {
        sliding: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
    },
  },
} satisfies Config;
